# Generated by Django 4.2.6 on 2024-01-11 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fullname', models.CharField(max_length=25)),
                ('Email', models.EmailField(max_length=254)),
                ('Gender', models.CharField(max_length=25)),
                ('Phonenumber', models.CharField(max_length=12)),
                ('DOB', models.CharField(max_length=25)),
                ('SelectMembershipplan', models.CharField(max_length=205)),
                ('Selecttrainer', models.CharField(max_length=205)),
                ('Reference', models.CharField(max_length=55)),
                ('Address', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Membershipplan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(max_length=25)),
                ('price', models.IntegerField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('gender', models.CharField(max_length=25)),
                ('phone', models.CharField(max_length=12)),
                ('salary', models.IntegerField(max_length=25)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
